import { Template } from './types';

export const PREMADE_TEMPLATES: Template[] = [
  {
    id: 'gte-response',
    name: 'GTECom Support AI',
    description: 'AI-powered customer service response generator for GTECom support.',
    category: 'Customer Support',
    icon: 'Sparkles',
    content: `# Customer Support Response
**To:** {{customer_name}}

---

### Original Response (English)
{{ai_generated_response}}

---

### Translation ({{target_language}})
{{ai_translated_response}}

---
**Agent Notes:** Generated by GTECom AI Engine`,
    fields: [
      { id: 'customer_name', label: 'Customer Name', type: 'text' },
      { id: 'customer_message', label: 'Customer Message', type: 'textarea', placeholder: 'Paste the customer email here...' },
      { id: 'resolution_details', label: 'Resolution & Steps', type: 'textarea', placeholder: 'What are the steps to fix this?' },
      { id: 'macro_name', label: 'Macro Name (Optional)', type: 'select', placeholder: 'Select a macro name...' },
      { id: 'internal_macro', label: 'Internal Macro / Template (Optional)', type: 'textarea', placeholder: 'Paste a specific macro or internal template to follow...' },
      { id: 'ai_generated_response', label: 'AI Output', type: 'textarea', placeholder: 'Click Generate to populate this field.' },
      { id: 'target_language', label: 'Target Language', type: 'text', defaultValue: 'Spanish', placeholder: 'Spanish, French, German, etc.' },
      { id: 'ai_translated_response', label: 'AI Translated Output', type: 'textarea', placeholder: 'Generated translation will appear here.' }
    ]
  }
];
